import { useState, type CSSProperties } from "react";
import DATA from "../data/skills.json";

// Real skill list, generated by docs/design/build_dashboard_skills.py. Icons
// stay on NCSoft's CDN (as in the meter's skillIcons.js), never in the repo.
export type GameSkill = {
  id: string;
  name: string;
  class: string;
  type: "Active" | "Chain" | "Stigma" | "Passive";
  icon: string;
  cd?: string;
  cast?: string;
  cost?: string;
  range?: string;
  desc?: string;
};
export const GAME_SKILLS = DATA as GameSkill[];
const ICON_BASE = "https://assets.playnccdn.com/static-aion2-gamedata/resources/";

export const classSkills = (cls: string) => GAME_SKILLS.filter((s) => s.class === cls);

/** The active character's class (onboarding), or Sorcerer when unset or without skill data (Brawler). */
export const planClass = (cls?: string) => (cls && classSkills(cls).length ? cls : "Sorcerer");

/** A skill by name, preferring the given class (several classes share names like "Shock Release"). */
export const findSkill = (name: string, cls?: string) =>
  GAME_SKILLS.find((s) => s.name === name && s.class === cls) ?? GAME_SKILLS.find((s) => s.name === name);

/** Up to two capitals of the name: the placeholder when there is no icon. */
export const skillInitials = (name: string) => name.replace(/[^A-Z]/g, "").slice(0, 2) || name.slice(0, 2);

/**
 * The skill's game icon, filling its (sized, shaped) parent. Unknown skill or
 * an icon that fails to load → the initials the pages showed before.
 */
export function SkillIcon({ skill, name, style }: { skill?: GameSkill; name: string; style?: CSSProperties }) {
  const [broken, setBroken] = useState<string>();
  const src = skill && ICON_BASE + skill.icon + ".png";
  if (!src || broken === src) return <>{skillInitials(name)}</>;
  return (
    <img
      src={src}
      alt=""
      loading="lazy"
      draggable={false}
      onError={() => setBroken(src)}
      style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: "inherit", display: "block", ...style }}
    />
  );
}
